# Generated by Django 5.2.13 on 2026-04-10 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_alat', models.CharField(max_length=200, verbose_name='Nama Alat')),
                ('merk', models.CharField(blank=True, max_length=100, verbose_name='Merk/Brand')),
                ('model_tipe', models.CharField(blank=True, max_length=100, verbose_name='Model/Tipe')),
                ('nomor_seri', models.CharField(max_length=100, unique=True, verbose_name='Nomor Seri')),
                ('pemilik', models.CharField(blank=True, max_length=200, verbose_name='Pemilik/Instansi')),
                ('lokasi', models.CharField(blank=True, max_length=200, verbose_name='Lokasi')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Alat/Instrumen',
                'verbose_name_plural': 'Alat/Instrumen',
                'ordering': ['nama_alat'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True, verbose_name='Nomor Sertifikat')),
                ('tanggal_kalibrasi', models.DateField(verbose_name='Tanggal Kalibrasi')),
                ('tanggal_berlaku', models.DateField(verbose_name='Berlaku Hingga')),
                ('laboratorium', models.CharField(max_length=200, verbose_name='Laboratorium')),
                ('teknisi', models.CharField(blank=True, max_length=200, verbose_name='Teknisi')),
                ('penanggung_jawab', models.CharField(blank=True, max_length=200, verbose_name='Penanggung Jawab')),
                ('file_sertifikat', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='File Sertifikat (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.instrument', verbose_name='Alat')),
            ],
            options={
                'verbose_name': 'Sertifikat Kalibrasi',
                'verbose_name_plural': 'Sertifikat Kalibrasi',
                'ordering': ['-tanggal_kalibrasi'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Lihat'), ('download', 'Download'), ('login_success', 'Login Berhasil'), ('login_failed', 'Login Gagal')], max_length=20, verbose_name='Aksi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Akses')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='certificates.certificate', verbose_name='Sertifikat')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='certificates.instrument', verbose_name='Alat')),
            ],
            options={
                'verbose_name': 'Log Akses',
                'verbose_name_plural': 'Log Akses',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('instansi', models.CharField(blank=True, max_length=200, verbose_name='Instansi/Perusahaan')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('scanner', 'Scanner')], default='scanner', max_length=10, verbose_name='Role')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Diblokir')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Percobaan Gagal')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diblokir')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
    ]
