# Generated by Django 5.2.13 on 2026-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['nomor_aset', 'nama_alat'], 'verbose_name': 'Alat/Instrumen', 'verbose_name_plural': 'Alat/Instrumen'},
        ),
        migrations.AddField(
            model_name='instrument',
            name='nomor_aset',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nomor Aset'),
        ),
    ]
